/**
 * Data Export Utilities
 * Export group data as CSV or PDF
 * Issue: #60
 */

export interface ContributionRecord {
  date: string;
  member: string;
  amount: string;
  round: number;
  status: 'pending' | 'completed';
}

export interface GroupSummary {
  name: string;
  id: number;
  createdAt: string;
  totalRounds: number;
  currentRound: number;
  totalContributed: string;
  members: string[];
  payouts: string[];
}

/**
 * Export contributions to CSV format
 */
export function exportContributionsCSV(contributions: ContributionRecord[], groupName: string): string {
  const headers = ['Date', 'Member', 'Amount', 'Round', 'Status'];
  const rows = contributions.map(c => [
    c.date,
    c.member,
    c.amount,
    c.round.toString(),
    c.status
  ]);

  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
  ].join('\n');

  return csvContent;
}

/**
 * Download CSV file
 */
export function downloadCSV(csvContent: string, filename: string): void {
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = filename;
  link.click();
  URL.revokeObjectURL(link.href);
}

/**
 * Export group summary as simple printable HTML (for PDF alternative)
 */
export function exportGroupSummaryPDF(group: GroupSummary, contributions: ContributionRecord[]): string {
  const html = `
<!DOCTYPE html>
<html>
<head>
  <title>${group.name} - Group Summary</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
    h1 { color: #333; border-bottom: 2px solid #4F46E5; padding-bottom: 10px; }
    h2 { color: #666; margin-top: 30px; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
    th { background-color: #f5f5f5; }
    .summary-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; margin: 20px 0; }
    .summary-item { background: #f9f9f9; padding: 15px; border-radius: 8px; }
    .summary-label { color: #666; font-size: 14px; }
    .summary-value { font-size: 24px; font-weight: bold; color: #333; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 12px; }
  </style>
</head>
<body>
  <h1>${group.name}</h1>
  <p>Group ID: ${group.id} | Created: ${group.createdAt}</p>

  <h2>Summary</h2>
  <div class="summary-grid">
    <div class="summary-item">
      <div class="summary-label">Total Rounds</div>
      <div class="summary-value">${group.totalRounds}</div>
    </div>
    <div class="summary-item">
      <div class="summary-label">Current Round</div>
      <div class="summary-value">${group.currentRound}</div>
    </div>
    <div class="summary-item">
      <div class="summary-label">Total Contributed</div>
      <div class="summary-value">${group.totalContributed}</div>
    </div>
    <div class="summary-item">
      <div class="summary-label">Members</div>
      <div class="summary-value">${group.members.length}</div>
    </div>
  </div>

  <h2>Contribution History</h2>
  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Member</th>
        <th>Amount</th>
        <th>Round</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      ${contributions.map(c => `
        <tr>
          <td>${c.date}</td>
          <td>${c.member}</td>
          <td>${c.amount}</td>
          <td>${c.round}</td>
          <td>${c.status}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <div class="footer">
    Generated by SoroSave on ${new Date().toLocaleDateString()}
  </div>
</body>
</html>
  `.trim();

  return html;
}

/**
 * Download as PDF (opens print dialog)
 */
export function downloadPDF(html: string, filename: string): void {
  const blob = new Blob([html], { type: 'text/html' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = filename.replace('.pdf', '.html');
  link.click();
  URL.revokeObjectURL(link.href);
  
  // Optionally trigger print dialog
  setTimeout(() => {
    window.print();
  }, 500);
}

/**
 * Main export function
 */
export async function exportGroupData(
  group: GroupSummary,
  contributions: ContributionRecord[],
  format: 'csv' | 'pdf'
): Promise<void> {
  const timestamp = new Date().toISOString().split('T')[0];
  const filename = `${group.name.replace(/\s+/g, '_')}_export_${timestamp}`;

  if (format === 'csv') {
    const csv = exportContributionsCSV(contributions, group.name);
    downloadCSV(csv, `${filename}.csv`);
  } else {
    const html = exportGroupSummaryPDF(group, contributions);
    downloadPDF(html, filename);
  }
}
